markdown:         rdiscount
pygments:         true
paginate:         6
permalink: /:year/:month/:title.html

title:            "Ant's Log on the Internet"
url:              http://blog.ownlinux.net
feed:             /atom.xml
author:
    name:         Ant
    email:        nourlcn@gmail.com
    skype:        nourlcn

description:      "Ant's life log -- record more "
about: 			  "微信扫描订阅本博客. "
follow:
    github:       https://github.com/nourlcn
    twitter:      https://twitter.com/nourlcn
style: 			  /css/style.css
blogName: 		  Ants Log
blogDesc: 		  Mac, BigData, Hadoop, Wechat, Life.
